[package]
name = "actix_demo"
version = "0.1.0"
authors = ["shaipe <shaipe@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.5"
actix = "*"
actix-web = "1.0.0"
actix-files = "0.1.1"
actix-rt = "0.2.2"
markdown="*"
futures = "0.1.25"
bytes = "0.4"
